export const FETCH_CAR_MAKE_LIST = "FETCH_CAR_MAKE_LIST";
export const FETCH_CAR_LIST = "FETCH_CAR_LIST";
export const SET_CAR_MAKE = "SET_CAR_MAKE";
export const SET_CAR_NAME = "SET_CAR_NAME";
export const FETCH_CAR_DETAILS = "FETCH_CAR_DETAILS";
export const SET_SELECTED_CAR_BUTTON_CLICK = "SET_SELECTED_CAR_BUTTON_CLICK";
export const FETCH_ERROR = "FETCH_ERROR";